---
title: "621 HW 1 v 4"
author: "Jeff Nieman, Scott Kahr, James Topor, Armenoush"
date: "June 13, 2016"
output: pdf_document
---


#####Creating a new column for batting singles and eliminating hits for batting
```{r}

mb_e <- read.csv("C:/Users/jenieman/Documents/CUNY/Data 621/moneyball-training-data.csv")  
#eliminate index column
mb_e1 <- mb_e[,-1]

#add singles column for hitting
mb_e1$TEAM_BATTING_1B <- as.numeric(mb_e1$TEAM_BATTING_H-mb_e1$TEAM_BATTING_2B-mb_e1$TEAM_BATTING_3B-mb_e1$TEAM_BATTING_HR)
mb_e1 <- mb_e1[,-2]
mb_e1 <- as.data.frame(mb_e1)
```

#####Eliminate HBP, CS, and pitching HR's.

```{r}
mb <- mb_e1[,-c(8,9,11)]
summary(mb)
```


#####Build model for batting SO using Gelman approach
```{r}
BSO <- lm(data=mb, TEAM_BATTING_SO~.)
summary(BSO)

#take out double plays + pitching SO + SB as data set is incomplete + Wins as they are not present in the evaluation data

BSO.1 <- lm(data=mb, TEAM_BATTING_SO~. -TEAM_FIELDING_DP -TEAM_PITCHING_SO -TEAM_BASERUN_SB -TARGET_WINS)
summary(BSO.1)

#eliminate doubles
BSO.2 <- lm(data=mb, TEAM_BATTING_SO~. -TEAM_FIELDING_DP -TEAM_PITCHING_SO -TEAM_BASERUN_SB - TARGET_WINS -TEAM_BATTING_2B)
summary(BSO.2)

##All p-values are low with a 686.8 F-statistic and adjusted R squared of 0.7236
#take a look
par(mfrow=c(2,2))
plot(BSO.2)
plot(BSO.2$residuals)

#prediction function
pred.BSO <- round(predict(BSO.2, mb))
impute <- function (a, a.impute){
  ifelse (is.na(a), a.impute,a)
}

BSO.imp <- impute(mb$TEAM_BATTING_SO, pred.BSO)

#place back in the data base with imputed data for SO's

mb1 <- mb
mb1$TEAM_BATTING_SO <- BSO.imp


```

#Build model for Pitching SO
```{r}
PSO <- lm(data=mb1, TEAM_PITCHING_SO~.)
summary(PSO)

#take out double plays + SB as data set is incomplete and wins as they are not present in evaluation data

PSO.1 <- lm(data=mb1, TEAM_PITCHING_SO~. -TEAM_FIELDING_DP -TEAM_BASERUN_SB - TARGET_WINS)
summary(PSO.1)

#all low P value and F statistic of 48090 with adj R squared of 0.9958
#take a look
par(mfrow=c(2,2))
plot(PSO.1)
plot(PSO.1$residuals)


#place back in the data base with imputed data for SO's
pred.PSO <- round(predict(PSO.1, mb1))
PSO.imp <- impute(mb1$TEAM_PITCHING_SO, pred.PSO)
mb2 <- mb1
mb2$TEAM_PITCHING_SO <- PSO.imp
```

#####Build model for SB
```{r}
SB <- lm(data=mb2, TEAM_BASERUN_SB~.)
summary(SB)

#Take out DP as incomplete data and target wins
SB.1 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP - TARGET_WINS)
summary(SB.1)

#eliminate pitching BB's
SB.2 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB - TARGET_WINS)
summary(SB.2)

#eliminate singles
SB.3 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB -TEAM_BATTING_1B - TARGET_WINS)
summary(SB.3)

#simplify the model by taking out pitching
SB.4 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB -TEAM_BATTING_1B - TARGET_WINS - TEAM_PITCHING_SO - TEAM_PITCHING_H)
summary(SB.4)

#add singles back in
SB.5 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB - TARGET_WINS - TEAM_PITCHING_SO - TEAM_PITCHING_H)
summary(SB.5)

#eliminate doubles
SB.6 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB - TARGET_WINS - TEAM_PITCHING_SO - TEAM_PITCHING_H - TEAM_BATTING_2B)
summary(SB.6)

#eliminate walks
SB.7 <- lm(data=mb2, TEAM_BASERUN_SB~.-TEAM_FIELDING_DP -TEAM_PITCHING_BB - TARGET_WINS - TEAM_PITCHING_SO - TEAM_PITCHING_H - TEAM_BATTING_2B - TEAM_BATTING_BB)
summary(SB.7)

#all low P value and F statistic of 202.1 with adj R squared of 0.3418
#take a look
par(mfrow=c(2,2))
plot(SB.7)
plot(SB.7$residuals)

#place back in the data base with imputed data for SB's
pred.SB <- round(predict(SB.7, mb2))
SB.imp <- impute(mb2$TEAM_BASERUN_SB, pred.SB)
mb3 <- mb2
mb3$TEAM_BASERUN_SB <- SB.imp
```

#####Build model to replace DP
```{r}
DP <- lm(data=mb3, TEAM_FIELDING_DP~.)
summary(DP)

#remove target wins
DP.1 <- lm(data=mb3, TEAM_FIELDING_DP~.-TARGET_WINS)
summary(DP.1)

#remove batting 2B's
DP.2 <- lm(data=mb3, TEAM_FIELDING_DP~.-TEAM_BATTING_2B -TARGET_WINS)
summary(DP.2)

#remove batting 1B's
DP.3 <- lm(data=mb3, TEAM_FIELDING_DP~.-TEAM_BATTING_2B -TARGET_WINS - TEAM_BATTING_1B)
summary(DP.3)

#remove batting 3B's
DP.4 <- lm(data=mb3, TEAM_FIELDING_DP~.-TEAM_BATTING_2B -TEAM_BATTING_3B - TEAM_BATTING_1B - TARGET_WINS)
summary(DP.4)


#all low P value and F statistic of 174.7 with adj R squared of 0.4113
#take a look
par(mfrow=c(2,2))
plot(DP.4)
plot(DP.4$residuals)

#place back in the data base with imputed data for SB's
pred.DP <- round(predict(DP.4, mb3))
DP.imp <- impute(mb3$TEAM_FIELDING_DP, pred.DP)
mb4 <- mb3
mb4$TEAM_FIELDING_DP <- DP.imp

#test new data set
summary(mb4)
```


#####Eliminate unhistorical outliers

```{r}

#most pitching SO's is 1450.  So delete all records with more than 1450 pitching SO's
mb5 <- mb4
mb5 <- mb5[which(mb1$TEAM_PITCHING_SO < 1450),]
summary(mb5)

#most ever hits by a team is 1730.  So delete all pitching hits >3000 to be conservative with the median
mb6 <- mb5
mb6 <- mb6[which(mb6$TEAM_PITCHING_H < 3001),]
summary(mb6)

#most ever errors by a team is 639 by 1883 Philadelphia.  Prorating to 162 games gives a value of 1046.
mb7 <- mb6
mb7 <- mb7[which(mb7$TEAM_FIELDING_E < 1047),]
summary(mb7)
dim(mb)-dim(mb7)
#we removed 206 rows total due to outliers.

```

